### ISSUE TITLE
unable to "select" content of a column

### ISSUE THREAD

**Issue by rmi7** [dwqs/v2-table#2]
I want to copy some content in a column in a row but I am unable to select any text in any row.

**Comment by dwqs** [comment]
yes, because I set the `user-select` style-rule  to `none` for table-cell element:

```css
.v2-table__cell {
    // ...
    user-select: none;
    // ...
}
```

you can override the style-rule to reach your aim.
